export const Images = {
    addNewUserWindow: require('../assets/images/addingnewuserwindow.png'),
    checkMachine: require('../assets/images/checkMachine.png'),
    girlPlanningBudget: require('../assets/images/Girlplanningbudgetwithtabletandpiggybank.png'),
    moneyAndPhone: require('../assets/images/moneyandphone.png'),
    openHomeSafe: require('../assets/images/openhomesafewithmoney.png'),
    piggyBank: require('../assets/images/Piggybankwithcoins.png'),
    wadofMoney: require('../assets/images/Wadofmoney.png'),
    walletWithCoin: require('../assets/images/walletwithcoinsandcreditcard.png'),
    youngwomansittingofloorinheadphones: require('../assets/images/youngwomansittingofloorinheadphones.png'),
    ProfilePic:require('../assets/images/ProfilePic.png')
}

export const Icons ={
    cameraIcon:require('../assets/icons/cameraIcon.png'),
    groupIcon:require('../assets/icons/groupIcon.png'),
    HelpIcon:require('../assets/icons/HelpIcon.png'),
    moneyIcon:require('../assets/icons/moneyIcon.png'),
    settingsIcon:require('../assets/icons/settingsIcon.png'),
    rupeesIcon:require('../assets/icons/rupeeIndian.png'),
    IncomeIcon:require('../assets/icons/ArrowDown.png'),
    ExpendetureIcon:require('../assets/icons/ArrowUp.png'),
    AddIcon:require('../assets/icons/addIcons.png'),
    Attachment:require('../assets/icons/attachment.png')
}

export const ExpensesIcon={
    Barber:require('../assets/icons/Expenses/Barber.png'),
    BusinessTravel:require('../assets/icons/Expenses/BusinessTravel.png'),
    babySittings:require('../assets/icons/Expenses/babySittings.png'),
    Carinsurance:require('../assets/icons/Expenses/Car-insurance.png'),
    clothsShopping:require('../assets/icons/Expenses/cloths-shhhopping.png'),
    CountinueEducation:require('../assets/icons/Expenses/CountinueEducation.png'),
    creditCard:require('../assets/icons/Expenses/creditCard.png'),
    Debt:require('../assets/icons/Expenses/Debt.png'),
    DiploamaAndDegree:require('../assets/icons/Expenses/DiploamaAndDegree.png'),
    Electricalsystem:require('../assets/icons/Expenses/Doctor.png'),
    ElectricalSystem:require('../assets/icons/Expenses/Electrical-system.png'),
    Electronics:require('../assets/icons/Expenses/Electronics.png'),
    emergencyFund:require('../assets/icons/Expenses/emergencyFund.png'),
    fastFood:require('../assets/icons/Expenses/fastFood.png'),
    Fruits:require('../assets/icons/Expenses/Fruits.png'),
    GasStationPetrol:require('../assets/icons/Expenses/Gas-station-Petrol.png'),
    gift:require('../assets/icons/Expenses/gift.png'),
    gymFitness:require('../assets/icons/Expenses/gym-Fitness.png'),
    HealthyFood:require('../assets/icons/Expenses/HealthyFood.png'),
    HomeDecure:require('../assets/icons/Expenses/HomeDecure.png'),
    houseGasCylinder:require('../assets/icons/Expenses/house-Gas-cylinder.png'),
    HomeInsurance:require('../assets/icons/Expenses/HomeInsurance.png'),
    Investment:require('../assets/icons/Expenses/Investment.png'),
    learningResources:require('../assets/icons/Expenses/learningResources.png'),
    mechaninc:require('../assets/icons/Expenses/mechaninc.png'),
    Medicines:require('../assets/icons/Expenses/Medicines.png'),
    MedicleInsurance:require('../assets/icons/Expenses/MedicleInsurance.png'),
    membership:require('../assets/icons/Expenses/membership.png'),
    MobileShopping:require('../assets/icons/Expenses/MobileShopping.png'),
    movies:require('../assets/icons/Expenses/movies.png'),
    Medication:require('../assets/icons/Expenses/Medication.png'),
    NutritionField:require('../assets/icons/Expenses/NutritionField.png'),
    OfficeSupplies:require('../assets/icons/Expenses/OfficeSupplies.png'),
    OnlineCourses:require('../assets/icons/Expenses/OnlineCourses.png'),
    OnlineLearning:require('../assets/icons/Expenses/OnlineLearning.png'),
    OnlineMedicineDelivery:require('../assets/icons/Expenses/OnlineMedicineDelivery.png'),
    OrderedFood:require('../assets/icons/Expenses/OrderedFood.png'),
    party:require('../assets/icons/Expenses/party.png'),
    PersonalTeaching:require('../assets/icons/Expenses/PersonalTeaching.png'),
    PetFood:require('../assets/icons/Expenses/PetFood.png'),
    rent:require('../assets/icons/Expenses/rent.png'),
    restaurents:require('../assets/icons/Expenses/restaurents.png'),
    retirementFund:require('../assets/icons/Expenses/retirementFund.png'),
    Router_Internet:require('../assets/icons/Expenses/Router_Internet.png'),
    School:require('../assets/icons/Expenses/School.png'),
    shoppingVehicle:require('../assets/icons/Expenses/shoppingVehicle.png'),
    Spa:require('../assets/icons/Expenses/Spa.png'),
    staffMoney:require('../assets/icons/Expenses/staffMoney.png'),
    subscription:require('../assets/icons/Expenses/subscription.png'),
    termlifeInsurance:require('../assets/icons/Expenses/termlifeInsurance.png'),
    Train_publicTransport:require('../assets/icons/Expenses/Train_publicTransport.png'),
    Travel:require('../assets/icons/Expenses/Travel.png'),
    travelInsurance:require('../assets/icons/Expenses/travelInsurance.png'),
    TvCabel:require('../assets/icons/Expenses/Tv-Cabel.png'),
    uberlikeTransportaion:require('../assets/icons/Expenses/uberlikeTransportaion.png'),
    Univercity:require('../assets/icons/Expenses/Univercity.png'),
    Water_bill:require('../assets/icons/Expenses/Water_bill.png'),
}
